config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <h1>All available flats (<%= @flats.count %>)</h1>
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="https://source.unsplash.com/1600x900/?apartment" alt="Card image cap">
          <div class="card-body bg-light">
            <h4 class="card-title"><%= flat.name %></h4>
            <p class="card-text"><%= flat.address %></p>
            <div class="d-flex align-items-end justify-content-start">
              <div class="d-flex justify-content-start">
                <i class="material-icons pr-2">people</i> <span class="pr-2"><%= flat.number_of_guests %></span>
              </div>
              <div class="d-flex justify-content-start">
                <i class="material-icons pr-2">euro_symbol</i> <span class="pr-2"><%= flat.price_per_night %></span>
              </div>
            </div>
          </div>
          <div class="card-body">
            <%= link_to 'More info', flat_path(flat) %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add a new flat</h1>
  <%= simple_form_for (@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Add flat",  class: "btn btn-primary" %>
    <%= link_to "Cancel", flats_path, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand">Simple AirBnB</a>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <button class="btn btn-success" type="button">
        <%= link_to 'Add flat', new_flat_path %>
      </button>
    </nav>
    <%= yield %>
  </body>
</html>